version: '3.7'
services:
  mysql:
    image: mysql:test
    container_name: mysqlDB_test
    platform: linux/amd64
    build:
      context: "./MySQL"
      dockerfile: "Dockerfile"
    ports:
      - "13306:3306"
    privileged: true
    volumes:
      - "$PWD/MySQL/mysql:/mysql"
