version: '3.7'
services:
  mysql:
    image: mysql:test
    container_name: mysqlDB_test
    platform: linux/amd64
    build:
      context: "./MySQL"
      dockerfile: "Dockerfile"
    ports:
      - "13306:3306"
    privileged: true
    volumes:
      - "$PWD/MySQL/mysql:/mysql"
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
    volumes:
      - $PWD/mongoDB/data:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
